name: pre-commit

# Runs pre-commit on the code being merged into main

on:
  pull_request:
  push:
    branches: [main, rust]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
